name: build-and-push-image

on:
  push:
    branches:
      - main

concurrency:
  group: "${{ github.repository_id }}-${{ github.event.pull_request.number}}"

jobs:
  build-and-push-test-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sharath94z
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          version: v0.9.1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            sharath94z/gaudiy
          flavor: |
            latest=false
          tags: |
            type=raw,value=${{ github.sha }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deployment:
    needs: build-and-push-test-image
    uses: ./.github/workflows/deployment-workflow.yaml
    with:
      kubernetes_namespace: applications
      docker_tag: ${{ github.sha }}
    secrets:
      gke_project: ${{ secrets.GKE_PROJECT }}
      gke_sa_key: ${{ secrets.GK_SA_KEY }}
